export const content = {
  en: {
    insertRowBefore: 'Add a line above',
    insertRowAfter: 'Add a line below',
    insertColLeft: 'Add a column to the left',
    insertColRight: 'Add a column to the right',
    align: 'Align type',
    removeRow: 'Remove this line',
    removeCol: 'Remove this column',
    removeTable: 'Remove this table',
    copyHtml: 'Copy table html',
    copyMarkdown: 'Copy table markdown',
    alignLeft: 'Align left',
    alignCenter: 'Align center',
    alignRight: 'Align right',
  },
  'zh-cn': {
    insertRowBefore: '上方增加行',
    insertRowAfter: '下方增加行',
    insertColLeft: '左侧增加列',
    insertColRight: '右侧增加列',
    align: '对齐方式',
    removeRow: '删除当前行',
    removeCol: '删除当前列',
    removeTable: '删除表格',
    copyHtml: '复制表格HTML',
    copyMarkdown: '复制表格md源码',
    alignLeft: '左对齐',
    alignCenter: '居中对齐',
    alignRight: '右对齐',
  },
  'zh-tw': {
    insertRowBefore: '上方增加行',
    insertRowAfter: '下方增加行',
    insertColLeft: '左側增加列',
    insertColRight: '右側增加列',
    align: '對齊方式',
    removeRow: '刪除當前行',
    removeCol: '删除當前列',
    removeTable: '删除表格',
    copyHtml: '複製表格HTML',
    copyMarkdown: '複製表格md源码',
    alignLeft: '左對齊',
    alignCenter: '居中對齊',
    alignRight: '右對齊',
  }
}